### ISSUE TITLE
https支持问题

### ISSUE THREAD

**Issue by tianhaoo** [liyangready/mini-proxy#3]
在使用http的时候很好用，但是https就会报下面的错，请问这是为什么？

```
$ curl -l "https://www.baidu.com"              
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.10.64.64:9393 
```

**Comment by liyangready** [comment]
你的代理是怎么设置的

Tianhaoo <notifications@github.com>于2018年8月26日 周日17:02写道：

**Comment by tianhaoo** [comment]
感谢回复，代理应该设置正确了，是这样设置的

在`~/.bashrc`文件中
```
export http_proxy="http://10.10.64.64:9393"
export https_proxy="https://10.10.64.64:9393"
```
我用wget运行了以下，发现可以正常使用，只有curl -l不可以。
不知道是什么原因，用curl的无法走这个https的代理，其他的一切都正常。

**Comment by liyangready** [comment]
恩，可能curl 和 https_proxy 结合有什么不一样的地方，还不是很清楚。

但是通过 curl -x http://127.0.0.1:9393 https://www.baidu.com 访问 https 是可以的

Tianhaoo <notifications@github.com> 于2018年8月26日周日 下午6:37写道：
