### ISSUE TITLE
请问通过 tunnel 的话 是不是不能根据 path 来设置代理？

### ISSUE THREAD

**Issue by lumixraku** [liyangready/mini-proxy#5]
请问通过 tunnel 的话 是不是不能根据 path 来设置代理？
因为在 connect 中只能得到 host port  没有 path
我想根据不同的 path 走不同的代理 可以吗

**Comment by liyangready** [comment]
不行的，如果要读path，需要加https证书了，类似中间人才能做到。

**Comment by lumixraku** [comment]
> 不行的，如果要读path，需要加https证书了，类似中间人才能做到。

👌
