### ISSUE TITLE
node 8+ ok 10+ 报错 能否支持一下

### ISSUE THREAD

**Issue by mj520** [liyangready/mini-proxy#8]
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: write ECONNABORTED
?[90m    at afterWriteDispatched (internal/stream_base_commons.js:150:25)?[39m
?[90m    at writeGeneric (internal/stream_base_commons.js:141:3)?[39m
?[90m    at Socket._writeGeneric (net.js:770:11)?[39m
?[90m    at Socket._write (net.js:782:8)?[39m
?[90m    at doWrite (_stream_writable.js:431:12)?[39m
?[90m    at writeOrBuffer (_stream_writable.js:415:5)?[39m
?[90m    at Socket.Writable.write (_stream_writable.js:305:11)?[39m
?[90m    at Socket.ondata (_stream_readable.js:726:22)?[39m
?[90m    at Socket.emit (events.js:210:5)?[39m
?[90m    at addChunk (_stream_readable.js:308:12)?[39m
Emitted 'error' event on Socket instance at:
?[90m    at errorOrDestroy (internal/streams/destroy.js:108:12)?[39m
?[90m    at Socket.onerror (_stream_readable.js:758:7)?[39m
?[90m    at Socket.emit (events.js:210:5)?[39m
?[90m    at errorOrDestroy (internal/streams/destroy.js:108:12)?[39m
?[90m    at onwriteError (_stream_writable.js:446:5)?[39m
?[90m    at onwrite (_stream_writable.js:473:5)?[39m
?[90m    at internal/streams/destroy.js:50:7?[39m
?[90m    at Socket._destroy (net.js:663:5)?[39m
?[90m    at Socket.destroy (internal/streams/destroy.js:38:8)?[39m
?[90m    at afterWriteDispatched (internal/stream_base_commons.js:150:17)?[39m {

  errno: ?[32m'ECONNABORTED'?[39m,
  code: ?[32m'ECONNABORTED'?[39m,
  syscall: ?[32m'write'?[39m
}

**Comment by liyangready** [comment]
![image](https://user-images.githubusercontent.com/5040076/70405475-4e489a00-1a78-11ea-9be0-ed130d5608c9.png)
有复现代码吗，本地测试好像没啥问题

**Comment by mj520** [comment]
https://github.com/mj520/multiple-host-env
重复访问，会报错

**Comment by liyangready** [comment]
已修复：https://github.com/liyangready/mini-proxy/commit/49c241c6c3ee687d4606e78e33cfcaaa28ea791c#diff-a5536ed1a2371648204c8acf15d5d06f
